name: fossil_scout
description: Fossil Scouting App MVP
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  uuid: ^4.5.1
  intl: ^0.20.2
  http: ^1.2.0
  google_polyline_algorithm: ^3.1.0
  exif: ^3.3.0
  image: ^4.3.0
  pointer_interceptor: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true